### PR TITLE
adding example for pixelui

### PR DESCRIPTION
**Pull request by dusk125**
Also made pixel-examples target `pixel/v2@main` to more easily pick up changes that haven't been released (but still need an example.)

### CODE REVIEW

**Comment by bhperry** [comment]
Assume we're waiting for the loader/atlas work to get hammered out before merging this since it uses atlas?

**Comment by dusk125** [comment]
> Assume we're waiting for the loader/atlas work to get hammered out before merging this since it uses atlas?

Yeah probably a good idea

**Comment by dusk125** [comment]
Image loading feature has merged, ptal @bhperry

**Review by bhperry — APPROVED** [review]
🥳

**Pull request merged**
